version: '3.8'

services:
  # Routing Engine (OSRM)
  osrm:
    image: osrm/osrm-backend
    container_name: osrm_india
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    command: osrm-routed --algorithm mld /data/india-260329.osrm
    restart: always

  # Map Tile Server (TileServer-GL)
  tileserver:
    image: maptiler/tileserver-gl
    container_name: tileserver_india
    ports:
      - "8765:8080"
    volumes:
      - ./data:/data
    command: --mbtiles /data/gujarat.mbtiles
    restart: always
