// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: api.proto
// Protobuf C++ Version: 6.33.4

#ifndef api_2eproto_2epb_2eh
#define api_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "options.pb.h"
#include "trip.pb.h"
#include "directions.pb.h"
#include "info.pb.h"
#include "status.pb.h"
#include "matrix.pb.h"
#include "isochrone.pb.h"
#include "expansion.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_api_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_api_2eproto {
  static const ::uint32_t offsets[];
};
namespace valhalla {
class Api;
struct ApiDefaultTypeInternal;
extern ApiDefaultTypeInternal _Api_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<13> Api_class_data_;
}  // namespace valhalla
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace valhalla {

// ===================================================================


// -------------------------------------------------------------------

class Api final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:valhalla.Api) */ {
 public:
  inline Api() : Api(nullptr) {}
  ~Api() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Api* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Api));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Api(::google::protobuf::internal::ConstantInitialized);

  inline Api(const Api& from) : Api(nullptr, from) {}
  inline Api(Api&& from) noexcept
      : Api(nullptr, ::std::move(from)) {}
  inline Api& operator=(const Api& from) {
    CopyFrom(from);
    return *this;
  }
  inline Api& operator=(Api&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const Api& default_instance() {
    return *reinterpret_cast<const Api*>(
        &_Api_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Api& a, Api& b) { a.Swap(&b); }
  inline void Swap(Api* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Api* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Api* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<Api>(arena);
  }
  void CopyFrom(const Api& from);
  void MergeFrom(const Api& from) { Api::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Api* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "valhalla.Api"; }

  explicit Api(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Api(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Api& from);
  Api(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Api&& from) noexcept
      : Api(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kOptionsFieldNumber = 1,
    kTripFieldNumber = 2,
    kDirectionsFieldNumber = 3,
    kStatusFieldNumber = 4,
    kMatrixFieldNumber = 5,
    kIsochroneFieldNumber = 6,
    kExpansionFieldNumber = 7,
    kInfoFieldNumber = 20,
  };
  // .valhalla.Options options = 1;
  bool has_options() const;
  void clear_options() ;
  const ::valhalla::Options& options() const;
  [[nodiscard]] ::valhalla::Options* PROTOBUF_NULLABLE release_options();
  ::valhalla::Options* PROTOBUF_NONNULL mutable_options();
  void set_allocated_options(::valhalla::Options* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_options(::valhalla::Options* PROTOBUF_NULLABLE value);
  ::valhalla::Options* PROTOBUF_NULLABLE unsafe_arena_release_options();

  private:
  const ::valhalla::Options& _internal_options() const;
  ::valhalla::Options* PROTOBUF_NONNULL _internal_mutable_options();

  public:
  // .valhalla.Trip trip = 2;
  bool has_trip() const;
  void clear_trip() ;
  const ::valhalla::Trip& trip() const;
  [[nodiscard]] ::valhalla::Trip* PROTOBUF_NULLABLE release_trip();
  ::valhalla::Trip* PROTOBUF_NONNULL mutable_trip();
  void set_allocated_trip(::valhalla::Trip* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_trip(::valhalla::Trip* PROTOBUF_NULLABLE value);
  ::valhalla::Trip* PROTOBUF_NULLABLE unsafe_arena_release_trip();

  private:
  const ::valhalla::Trip& _internal_trip() const;
  ::valhalla::Trip* PROTOBUF_NONNULL _internal_mutable_trip();

  public:
  // .valhalla.Directions directions = 3;
  bool has_directions() const;
  void clear_directions() ;
  const ::valhalla::Directions& directions() const;
  [[nodiscard]] ::valhalla::Directions* PROTOBUF_NULLABLE release_directions();
  ::valhalla::Directions* PROTOBUF_NONNULL mutable_directions();
  void set_allocated_directions(::valhalla::Directions* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_directions(::valhalla::Directions* PROTOBUF_NULLABLE value);
  ::valhalla::Directions* PROTOBUF_NULLABLE unsafe_arena_release_directions();

  private:
  const ::valhalla::Directions& _internal_directions() const;
  ::valhalla::Directions* PROTOBUF_NONNULL _internal_mutable_directions();

  public:
  // .valhalla.Status status = 4;
  bool has_status() const;
  void clear_status() ;
  const ::valhalla::Status& status() const;
  [[nodiscard]] ::valhalla::Status* PROTOBUF_NULLABLE release_status();
  ::valhalla::Status* PROTOBUF_NONNULL mutable_status();
  void set_allocated_status(::valhalla::Status* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_status(::valhalla::Status* PROTOBUF_NULLABLE value);
  ::valhalla::Status* PROTOBUF_NULLABLE unsafe_arena_release_status();

  private:
  const ::valhalla::Status& _internal_status() const;
  ::valhalla::Status* PROTOBUF_NONNULL _internal_mutable_status();

  public:
  // .valhalla.Matrix matrix = 5;
  bool has_matrix() const;
  void clear_matrix() ;
  const ::valhalla::Matrix& matrix() const;
  [[nodiscard]] ::valhalla::Matrix* PROTOBUF_NULLABLE release_matrix();
  ::valhalla::Matrix* PROTOBUF_NONNULL mutable_matrix();
  void set_allocated_matrix(::valhalla::Matrix* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_matrix(::valhalla::Matrix* PROTOBUF_NULLABLE value);
  ::valhalla::Matrix* PROTOBUF_NULLABLE unsafe_arena_release_matrix();

  private:
  const ::valhalla::Matrix& _internal_matrix() const;
  ::valhalla::Matrix* PROTOBUF_NONNULL _internal_mutable_matrix();

  public:
  // .valhalla.Isochrone isochrone = 6;
  bool has_isochrone() const;
  void clear_isochrone() ;
  const ::valhalla::Isochrone& isochrone() const;
  [[nodiscard]] ::valhalla::Isochrone* PROTOBUF_NULLABLE release_isochrone();
  ::valhalla::Isochrone* PROTOBUF_NONNULL mutable_isochrone();
  void set_allocated_isochrone(::valhalla::Isochrone* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_isochrone(::valhalla::Isochrone* PROTOBUF_NULLABLE value);
  ::valhalla::Isochrone* PROTOBUF_NULLABLE unsafe_arena_release_isochrone();

  private:
  const ::valhalla::Isochrone& _internal_isochrone() const;
  ::valhalla::Isochrone* PROTOBUF_NONNULL _internal_mutable_isochrone();

  public:
  // .valhalla.Expansion expansion = 7;
  bool has_expansion() const;
  void clear_expansion() ;
  const ::valhalla::Expansion& expansion() const;
  [[nodiscard]] ::valhalla::Expansion* PROTOBUF_NULLABLE release_expansion();
  ::valhalla::Expansion* PROTOBUF_NONNULL mutable_expansion();
  void set_allocated_expansion(::valhalla::Expansion* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_expansion(::valhalla::Expansion* PROTOBUF_NULLABLE value);
  ::valhalla::Expansion* PROTOBUF_NULLABLE unsafe_arena_release_expansion();

  private:
  const ::valhalla::Expansion& _internal_expansion() const;
  ::valhalla::Expansion* PROTOBUF_NONNULL _internal_mutable_expansion();

  public:
  // .valhalla.Info info = 20;
  bool has_info() const;
  void clear_info() ;
  const ::valhalla::Info& info() const;
  [[nodiscard]] ::valhalla::Info* PROTOBUF_NULLABLE release_info();
  ::valhalla::Info* PROTOBUF_NONNULL mutable_info();
  void set_allocated_info(::valhalla::Info* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_info(::valhalla::Info* PROTOBUF_NULLABLE value);
  ::valhalla::Info* PROTOBUF_NULLABLE unsafe_arena_release_info();

  private:
  const ::valhalla::Info& _internal_info() const;
  ::valhalla::Info* PROTOBUF_NONNULL _internal_mutable_info();

  public:
  // @@protoc_insertion_point(class_scope:valhalla.Api)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8,
                                   8, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Api& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::valhalla::Options* PROTOBUF_NULLABLE options_;
    ::valhalla::Trip* PROTOBUF_NULLABLE trip_;
    ::valhalla::Directions* PROTOBUF_NULLABLE directions_;
    ::valhalla::Status* PROTOBUF_NULLABLE status_;
    ::valhalla::Matrix* PROTOBUF_NULLABLE matrix_;
    ::valhalla::Isochrone* PROTOBUF_NULLABLE isochrone_;
    ::valhalla::Expansion* PROTOBUF_NULLABLE expansion_;
    ::valhalla::Info* PROTOBUF_NULLABLE info_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_api_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<13> Api_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Api

// .valhalla.Options options = 1;
inline bool Api::has_options() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.options_ != nullptr);
  return value;
}
inline const ::valhalla::Options& Api::_internal_options() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::valhalla::Options* p = _impl_.options_;
  return p != nullptr ? *p : reinterpret_cast<const ::valhalla::Options&>(::valhalla::_Options_default_instance_);
}
inline const ::valhalla::Options& Api::options() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Api.options)
  return _internal_options();
}
inline void Api::unsafe_arena_set_allocated_options(
    ::valhalla::Options* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.options_);
  }
  _impl_.options_ = reinterpret_cast<::valhalla::Options*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:valhalla.Api.options)
}
inline ::valhalla::Options* PROTOBUF_NULLABLE Api::release_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::valhalla::Options* released = _impl_.options_;
  _impl_.options_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::valhalla::Options* PROTOBUF_NULLABLE Api::unsafe_arena_release_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:valhalla.Api.options)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::valhalla::Options* temp = _impl_.options_;
  _impl_.options_ = nullptr;
  return temp;
}
inline ::valhalla::Options* PROTOBUF_NONNULL Api::_internal_mutable_options() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.options_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::valhalla::Options>(GetArena());
    _impl_.options_ = reinterpret_cast<::valhalla::Options*>(p);
  }
  return _impl_.options_;
}
inline ::valhalla::Options* PROTOBUF_NONNULL Api::mutable_options()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::valhalla::Options* _msg = _internal_mutable_options();
  // @@protoc_insertion_point(field_mutable:valhalla.Api.options)
  return _msg;
}
inline void Api::set_allocated_options(::valhalla::Options* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.options_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.options_ = reinterpret_cast<::valhalla::Options*>(value);
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.options)
}

// .valhalla.Trip trip = 2;
inline bool Api::has_trip() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.trip_ != nullptr);
  return value;
}
inline const ::valhalla::Trip& Api::_internal_trip() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::valhalla::Trip* p = _impl_.trip_;
  return p != nullptr ? *p : reinterpret_cast<const ::valhalla::Trip&>(::valhalla::_Trip_default_instance_);
}
inline const ::valhalla::Trip& Api::trip() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Api.trip)
  return _internal_trip();
}
inline void Api::unsafe_arena_set_allocated_trip(
    ::valhalla::Trip* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.trip_);
  }
  _impl_.trip_ = reinterpret_cast<::valhalla::Trip*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:valhalla.Api.trip)
}
inline ::valhalla::Trip* PROTOBUF_NULLABLE Api::release_trip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::valhalla::Trip* released = _impl_.trip_;
  _impl_.trip_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::valhalla::Trip* PROTOBUF_NULLABLE Api::unsafe_arena_release_trip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:valhalla.Api.trip)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::valhalla::Trip* temp = _impl_.trip_;
  _impl_.trip_ = nullptr;
  return temp;
}
inline ::valhalla::Trip* PROTOBUF_NONNULL Api::_internal_mutable_trip() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.trip_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::valhalla::Trip>(GetArena());
    _impl_.trip_ = reinterpret_cast<::valhalla::Trip*>(p);
  }
  return _impl_.trip_;
}
inline ::valhalla::Trip* PROTOBUF_NONNULL Api::mutable_trip()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::valhalla::Trip* _msg = _internal_mutable_trip();
  // @@protoc_insertion_point(field_mutable:valhalla.Api.trip)
  return _msg;
}
inline void Api::set_allocated_trip(::valhalla::Trip* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.trip_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.trip_ = reinterpret_cast<::valhalla::Trip*>(value);
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.trip)
}

// .valhalla.Directions directions = 3;
inline bool Api::has_directions() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  PROTOBUF_ASSUME(!value || _impl_.directions_ != nullptr);
  return value;
}
inline const ::valhalla::Directions& Api::_internal_directions() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::valhalla::Directions* p = _impl_.directions_;
  return p != nullptr ? *p : reinterpret_cast<const ::valhalla::Directions&>(::valhalla::_Directions_default_instance_);
}
inline const ::valhalla::Directions& Api::directions() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Api.directions)
  return _internal_directions();
}
inline void Api::unsafe_arena_set_allocated_directions(
    ::valhalla::Directions* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.directions_);
  }
  _impl_.directions_ = reinterpret_cast<::valhalla::Directions*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:valhalla.Api.directions)
}
inline ::valhalla::Directions* PROTOBUF_NULLABLE Api::release_directions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::valhalla::Directions* released = _impl_.directions_;
  _impl_.directions_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::valhalla::Directions* PROTOBUF_NULLABLE Api::unsafe_arena_release_directions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:valhalla.Api.directions)

  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::valhalla::Directions* temp = _impl_.directions_;
  _impl_.directions_ = nullptr;
  return temp;
}
inline ::valhalla::Directions* PROTOBUF_NONNULL Api::_internal_mutable_directions() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.directions_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::valhalla::Directions>(GetArena());
    _impl_.directions_ = reinterpret_cast<::valhalla::Directions*>(p);
  }
  return _impl_.directions_;
}
inline ::valhalla::Directions* PROTOBUF_NONNULL Api::mutable_directions()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::valhalla::Directions* _msg = _internal_mutable_directions();
  // @@protoc_insertion_point(field_mutable:valhalla.Api.directions)
  return _msg;
}
inline void Api::set_allocated_directions(::valhalla::Directions* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.directions_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }

  _impl_.directions_ = reinterpret_cast<::valhalla::Directions*>(value);
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.directions)
}

// .valhalla.Status status = 4;
inline bool Api::has_status() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  PROTOBUF_ASSUME(!value || _impl_.status_ != nullptr);
  return value;
}
inline const ::valhalla::Status& Api::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::valhalla::Status* p = _impl_.status_;
  return p != nullptr ? *p : reinterpret_cast<const ::valhalla::Status&>(::valhalla::_Status_default_instance_);
}
inline const ::valhalla::Status& Api::status() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Api.status)
  return _internal_status();
}
inline void Api::unsafe_arena_set_allocated_status(
    ::valhalla::Status* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.status_);
  }
  _impl_.status_ = reinterpret_cast<::valhalla::Status*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:valhalla.Api.status)
}
inline ::valhalla::Status* PROTOBUF_NULLABLE Api::release_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::valhalla::Status* released = _impl_.status_;
  _impl_.status_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::valhalla::Status* PROTOBUF_NULLABLE Api::unsafe_arena_release_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:valhalla.Api.status)

  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::valhalla::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
  return temp;
}
inline ::valhalla::Status* PROTOBUF_NONNULL Api::_internal_mutable_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.status_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::valhalla::Status>(GetArena());
    _impl_.status_ = reinterpret_cast<::valhalla::Status*>(p);
  }
  return _impl_.status_;
}
inline ::valhalla::Status* PROTOBUF_NONNULL Api::mutable_status()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::valhalla::Status* _msg = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:valhalla.Api.status)
  return _msg;
}
inline void Api::set_allocated_status(::valhalla::Status* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.status_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }

  _impl_.status_ = reinterpret_cast<::valhalla::Status*>(value);
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.status)
}

// .valhalla.Matrix matrix = 5;
inline bool Api::has_matrix() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  PROTOBUF_ASSUME(!value || _impl_.matrix_ != nullptr);
  return value;
}
inline const ::valhalla::Matrix& Api::_internal_matrix() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::valhalla::Matrix* p = _impl_.matrix_;
  return p != nullptr ? *p : reinterpret_cast<const ::valhalla::Matrix&>(::valhalla::_Matrix_default_instance_);
}
inline const ::valhalla::Matrix& Api::matrix() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Api.matrix)
  return _internal_matrix();
}
inline void Api::unsafe_arena_set_allocated_matrix(
    ::valhalla::Matrix* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.matrix_);
  }
  _impl_.matrix_ = reinterpret_cast<::valhalla::Matrix*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:valhalla.Api.matrix)
}
inline ::valhalla::Matrix* PROTOBUF_NULLABLE Api::release_matrix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::valhalla::Matrix* released = _impl_.matrix_;
  _impl_.matrix_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::valhalla::Matrix* PROTOBUF_NULLABLE Api::unsafe_arena_release_matrix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:valhalla.Api.matrix)

  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::valhalla::Matrix* temp = _impl_.matrix_;
  _impl_.matrix_ = nullptr;
  return temp;
}
inline ::valhalla::Matrix* PROTOBUF_NONNULL Api::_internal_mutable_matrix() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.matrix_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::valhalla::Matrix>(GetArena());
    _impl_.matrix_ = reinterpret_cast<::valhalla::Matrix*>(p);
  }
  return _impl_.matrix_;
}
inline ::valhalla::Matrix* PROTOBUF_NONNULL Api::mutable_matrix()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::valhalla::Matrix* _msg = _internal_mutable_matrix();
  // @@protoc_insertion_point(field_mutable:valhalla.Api.matrix)
  return _msg;
}
inline void Api::set_allocated_matrix(::valhalla::Matrix* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.matrix_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }

  _impl_.matrix_ = reinterpret_cast<::valhalla::Matrix*>(value);
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.matrix)
}

// .valhalla.Isochrone isochrone = 6;
inline bool Api::has_isochrone() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  PROTOBUF_ASSUME(!value || _impl_.isochrone_ != nullptr);
  return value;
}
inline const ::valhalla::Isochrone& Api::_internal_isochrone() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::valhalla::Isochrone* p = _impl_.isochrone_;
  return p != nullptr ? *p : reinterpret_cast<const ::valhalla::Isochrone&>(::valhalla::_Isochrone_default_instance_);
}
inline const ::valhalla::Isochrone& Api::isochrone() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Api.isochrone)
  return _internal_isochrone();
}
inline void Api::unsafe_arena_set_allocated_isochrone(
    ::valhalla::Isochrone* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.isochrone_);
  }
  _impl_.isochrone_ = reinterpret_cast<::valhalla::Isochrone*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:valhalla.Api.isochrone)
}
inline ::valhalla::Isochrone* PROTOBUF_NULLABLE Api::release_isochrone() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::valhalla::Isochrone* released = _impl_.isochrone_;
  _impl_.isochrone_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::valhalla::Isochrone* PROTOBUF_NULLABLE Api::unsafe_arena_release_isochrone() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:valhalla.Api.isochrone)

  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::valhalla::Isochrone* temp = _impl_.isochrone_;
  _impl_.isochrone_ = nullptr;
  return temp;
}
inline ::valhalla::Isochrone* PROTOBUF_NONNULL Api::_internal_mutable_isochrone() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.isochrone_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::valhalla::Isochrone>(GetArena());
    _impl_.isochrone_ = reinterpret_cast<::valhalla::Isochrone*>(p);
  }
  return _impl_.isochrone_;
}
inline ::valhalla::Isochrone* PROTOBUF_NONNULL Api::mutable_isochrone()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::valhalla::Isochrone* _msg = _internal_mutable_isochrone();
  // @@protoc_insertion_point(field_mutable:valhalla.Api.isochrone)
  return _msg;
}
inline void Api::set_allocated_isochrone(::valhalla::Isochrone* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.isochrone_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }

  _impl_.isochrone_ = reinterpret_cast<::valhalla::Isochrone*>(value);
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.isochrone)
}

// .valhalla.Expansion expansion = 7;
inline bool Api::has_expansion() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  PROTOBUF_ASSUME(!value || _impl_.expansion_ != nullptr);
  return value;
}
inline const ::valhalla::Expansion& Api::_internal_expansion() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::valhalla::Expansion* p = _impl_.expansion_;
  return p != nullptr ? *p : reinterpret_cast<const ::valhalla::Expansion&>(::valhalla::_Expansion_default_instance_);
}
inline const ::valhalla::Expansion& Api::expansion() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Api.expansion)
  return _internal_expansion();
}
inline void Api::unsafe_arena_set_allocated_expansion(
    ::valhalla::Expansion* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.expansion_);
  }
  _impl_.expansion_ = reinterpret_cast<::valhalla::Expansion*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:valhalla.Api.expansion)
}
inline ::valhalla::Expansion* PROTOBUF_NULLABLE Api::release_expansion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::valhalla::Expansion* released = _impl_.expansion_;
  _impl_.expansion_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::valhalla::Expansion* PROTOBUF_NULLABLE Api::unsafe_arena_release_expansion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:valhalla.Api.expansion)

  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::valhalla::Expansion* temp = _impl_.expansion_;
  _impl_.expansion_ = nullptr;
  return temp;
}
inline ::valhalla::Expansion* PROTOBUF_NONNULL Api::_internal_mutable_expansion() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.expansion_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::valhalla::Expansion>(GetArena());
    _impl_.expansion_ = reinterpret_cast<::valhalla::Expansion*>(p);
  }
  return _impl_.expansion_;
}
inline ::valhalla::Expansion* PROTOBUF_NONNULL Api::mutable_expansion()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::valhalla::Expansion* _msg = _internal_mutable_expansion();
  // @@protoc_insertion_point(field_mutable:valhalla.Api.expansion)
  return _msg;
}
inline void Api::set_allocated_expansion(::valhalla::Expansion* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.expansion_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  }

  _impl_.expansion_ = reinterpret_cast<::valhalla::Expansion*>(value);
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.expansion)
}

// .valhalla.Info info = 20;
inline bool Api::has_info() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  PROTOBUF_ASSUME(!value || _impl_.info_ != nullptr);
  return value;
}
inline const ::valhalla::Info& Api::_internal_info() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::valhalla::Info* p = _impl_.info_;
  return p != nullptr ? *p : reinterpret_cast<const ::valhalla::Info&>(::valhalla::_Info_default_instance_);
}
inline const ::valhalla::Info& Api::info() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Api.info)
  return _internal_info();
}
inline void Api::unsafe_arena_set_allocated_info(
    ::valhalla::Info* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.info_);
  }
  _impl_.info_ = reinterpret_cast<::valhalla::Info*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:valhalla.Api.info)
}
inline ::valhalla::Info* PROTOBUF_NULLABLE Api::release_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
  ::valhalla::Info* released = _impl_.info_;
  _impl_.info_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::valhalla::Info* PROTOBUF_NULLABLE Api::unsafe_arena_release_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:valhalla.Api.info)

  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
  ::valhalla::Info* temp = _impl_.info_;
  _impl_.info_ = nullptr;
  return temp;
}
inline ::valhalla::Info* PROTOBUF_NONNULL Api::_internal_mutable_info() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.info_ == nullptr) {
    auto* p = ::google::protobuf::MessageLite::DefaultConstruct<::valhalla::Info>(GetArena());
    _impl_.info_ = reinterpret_cast<::valhalla::Info*>(p);
  }
  return _impl_.info_;
}
inline ::valhalla::Info* PROTOBUF_NONNULL Api::mutable_info()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  ::valhalla::Info* _msg = _internal_mutable_info();
  // @@protoc_insertion_point(field_mutable:valhalla.Api.info)
  return _msg;
}
inline void Api::set_allocated_info(::valhalla::Info* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.info_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
  }

  _impl_.info_ = reinterpret_cast<::valhalla::Info*>(value);
  // @@protoc_insertion_point(field_set_allocated:valhalla.Api.info)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace valhalla


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // api_2eproto_2epb_2eh
