// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: expansion.proto
// Protobuf C++ Version: 6.33.4

#ifndef expansion_2eproto_2epb_2eh
#define expansion_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_expansion_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_expansion_2eproto {
  static const ::uint32_t offsets[];
};
namespace valhalla {
enum Expansion_EdgeStatus : int;
extern const uint32_t Expansion_EdgeStatus_internal_data_[];
enum Expansion_ExpansionType : int;
extern const uint32_t Expansion_ExpansionType_internal_data_[];
class Expansion;
struct ExpansionDefaultTypeInternal;
extern ExpansionDefaultTypeInternal _Expansion_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<19> Expansion_class_data_;
class Expansion_Geometry;
struct Expansion_GeometryDefaultTypeInternal;
extern Expansion_GeometryDefaultTypeInternal _Expansion_Geometry_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<28> Expansion_Geometry_class_data_;
}  // namespace valhalla
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::valhalla::Expansion_EdgeStatus_internal_data_>
    internal::EnumTraitsImpl::value<::valhalla::Expansion_EdgeStatus>;
template <>
internal::EnumTraitsT<::valhalla::Expansion_ExpansionType_internal_data_>
    internal::EnumTraitsImpl::value<::valhalla::Expansion_ExpansionType>;
}  // namespace protobuf
}  // namespace google

namespace valhalla {
enum Expansion_EdgeStatus : int {
  Expansion_EdgeStatus_connected = 0,
  Expansion_EdgeStatus_settled = 1,
  Expansion_EdgeStatus_reached = 2,
  Expansion_EdgeStatus_Expansion_EdgeStatus_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Expansion_EdgeStatus_Expansion_EdgeStatus_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Expansion_EdgeStatus_internal_data_[];
inline constexpr Expansion_EdgeStatus Expansion_EdgeStatus_EdgeStatus_MIN =
    static_cast<Expansion_EdgeStatus>(0);
inline constexpr Expansion_EdgeStatus Expansion_EdgeStatus_EdgeStatus_MAX =
    static_cast<Expansion_EdgeStatus>(2);
inline bool Expansion_EdgeStatus_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Expansion_EdgeStatus_EdgeStatus_ARRAYSIZE = 2 + 1;
const ::std::string& Expansion_EdgeStatus_Name(Expansion_EdgeStatus value);
template <typename T>
const ::std::string& Expansion_EdgeStatus_Name(T value) {
  static_assert(::std::is_same<T, Expansion_EdgeStatus>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EdgeStatus_Name().");
  return Expansion_EdgeStatus_Name(static_cast<Expansion_EdgeStatus>(value));
}
bool Expansion_EdgeStatus_Parse(
    ::absl::string_view name, Expansion_EdgeStatus* PROTOBUF_NONNULL value);
enum Expansion_ExpansionType : int {
  Expansion_ExpansionType_forward = 0,
  Expansion_ExpansionType_reverse = 1,
  Expansion_ExpansionType_Expansion_ExpansionType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Expansion_ExpansionType_Expansion_ExpansionType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Expansion_ExpansionType_internal_data_[];
inline constexpr Expansion_ExpansionType Expansion_ExpansionType_ExpansionType_MIN =
    static_cast<Expansion_ExpansionType>(0);
inline constexpr Expansion_ExpansionType Expansion_ExpansionType_ExpansionType_MAX =
    static_cast<Expansion_ExpansionType>(1);
inline bool Expansion_ExpansionType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int Expansion_ExpansionType_ExpansionType_ARRAYSIZE = 1 + 1;
const ::std::string& Expansion_ExpansionType_Name(Expansion_ExpansionType value);
template <typename T>
const ::std::string& Expansion_ExpansionType_Name(T value) {
  static_assert(::std::is_same<T, Expansion_ExpansionType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ExpansionType_Name().");
  return Expansion_ExpansionType_Name(static_cast<Expansion_ExpansionType>(value));
}
bool Expansion_ExpansionType_Parse(
    ::absl::string_view name, Expansion_ExpansionType* PROTOBUF_NONNULL value);

// ===================================================================


// -------------------------------------------------------------------

class Expansion_Geometry final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:valhalla.Expansion.Geometry) */ {
 public:
  inline Expansion_Geometry() : Expansion_Geometry(nullptr) {}
  ~Expansion_Geometry() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Expansion_Geometry* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Expansion_Geometry));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Expansion_Geometry(::google::protobuf::internal::ConstantInitialized);

  inline Expansion_Geometry(const Expansion_Geometry& from) : Expansion_Geometry(nullptr, from) {}
  inline Expansion_Geometry(Expansion_Geometry&& from) noexcept
      : Expansion_Geometry(nullptr, ::std::move(from)) {}
  inline Expansion_Geometry& operator=(const Expansion_Geometry& from) {
    CopyFrom(from);
    return *this;
  }
  inline Expansion_Geometry& operator=(Expansion_Geometry&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const Expansion_Geometry& default_instance() {
    return *reinterpret_cast<const Expansion_Geometry*>(
        &_Expansion_Geometry_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Expansion_Geometry& a, Expansion_Geometry& b) { a.Swap(&b); }
  inline void Swap(Expansion_Geometry* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Expansion_Geometry* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Expansion_Geometry* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<Expansion_Geometry>(arena);
  }
  void CopyFrom(const Expansion_Geometry& from);
  void MergeFrom(const Expansion_Geometry& from) { Expansion_Geometry::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Expansion_Geometry* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "valhalla.Expansion.Geometry"; }

  explicit Expansion_Geometry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Expansion_Geometry(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Expansion_Geometry& from);
  Expansion_Geometry(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Expansion_Geometry&& from) noexcept
      : Expansion_Geometry(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCoordsFieldNumber = 1,
  };
  // repeated sint32 coords = 1 [packed = true];
  int coords_size() const;
  private:
  int _internal_coords_size() const;

  public:
  void clear_coords() ;
  ::int32_t coords(int index) const;
  void set_coords(int index, ::int32_t value);
  void add_coords(::int32_t value);
  const ::google::protobuf::RepeatedField<::int32_t>& coords() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL mutable_coords();

  private:
  const ::google::protobuf::RepeatedField<::int32_t>& _internal_coords() const;
  ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL _internal_mutable_coords();

  public:
  // @@protoc_insertion_point(class_scope:valhalla.Expansion.Geometry)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Expansion_Geometry& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::int32_t> coords_;
    ::google::protobuf::internal::CachedSize _coords_cached_byte_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_expansion_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<28> Expansion_Geometry_class_data_;
// -------------------------------------------------------------------

class Expansion final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:valhalla.Expansion) */ {
 public:
  inline Expansion() : Expansion(nullptr) {}
  ~Expansion() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Expansion* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Expansion));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Expansion(::google::protobuf::internal::ConstantInitialized);

  inline Expansion(const Expansion& from) : Expansion(nullptr, from) {}
  inline Expansion(Expansion&& from) noexcept
      : Expansion(nullptr, ::std::move(from)) {}
  inline Expansion& operator=(const Expansion& from) {
    CopyFrom(from);
    return *this;
  }
  inline Expansion& operator=(Expansion&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const Expansion& default_instance() {
    return *reinterpret_cast<const Expansion*>(
        &_Expansion_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Expansion& a, Expansion& b) { a.Swap(&b); }
  inline void Swap(Expansion* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Expansion* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Expansion* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<Expansion>(arena);
  }
  void CopyFrom(const Expansion& from);
  void MergeFrom(const Expansion& from) { Expansion::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Expansion* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "valhalla.Expansion"; }

  explicit Expansion(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Expansion(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Expansion& from);
  Expansion(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Expansion&& from) noexcept
      : Expansion(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------
  using Geometry = Expansion_Geometry;
  using EdgeStatus = Expansion_EdgeStatus;
  static constexpr EdgeStatus connected = Expansion_EdgeStatus_connected;
  static constexpr EdgeStatus settled = Expansion_EdgeStatus_settled;
  static constexpr EdgeStatus reached = Expansion_EdgeStatus_reached;
  static inline bool EdgeStatus_IsValid(int value) {
    return Expansion_EdgeStatus_IsValid(value);
  }
  static constexpr EdgeStatus EdgeStatus_MIN = Expansion_EdgeStatus_EdgeStatus_MIN;
  static constexpr EdgeStatus EdgeStatus_MAX = Expansion_EdgeStatus_EdgeStatus_MAX;
  static constexpr int EdgeStatus_ARRAYSIZE = Expansion_EdgeStatus_EdgeStatus_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& EdgeStatus_Name(T value) {
    return Expansion_EdgeStatus_Name(value);
  }
  static inline bool EdgeStatus_Parse(
      ::absl::string_view name, EdgeStatus* PROTOBUF_NONNULL value) {
    return Expansion_EdgeStatus_Parse(name, value);
  }
  using ExpansionType = Expansion_ExpansionType;
  static constexpr ExpansionType forward = Expansion_ExpansionType_forward;
  static constexpr ExpansionType reverse = Expansion_ExpansionType_reverse;
  static inline bool ExpansionType_IsValid(int value) {
    return Expansion_ExpansionType_IsValid(value);
  }
  static constexpr ExpansionType ExpansionType_MIN = Expansion_ExpansionType_ExpansionType_MIN;
  static constexpr ExpansionType ExpansionType_MAX = Expansion_ExpansionType_ExpansionType_MAX;
  static constexpr int ExpansionType_ARRAYSIZE = Expansion_ExpansionType_ExpansionType_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& ExpansionType_Name(T value) {
    return Expansion_ExpansionType_Name(value);
  }
  static inline bool ExpansionType_Parse(
      ::absl::string_view name, ExpansionType* PROTOBUF_NONNULL value) {
    return Expansion_ExpansionType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kCostsFieldNumber = 1,
    kDurationsFieldNumber = 2,
    kDistancesFieldNumber = 3,
    kEdgeStatusFieldNumber = 4,
    kEdgeIdFieldNumber = 5,
    kPredEdgeIdFieldNumber = 6,
    kGeometriesFieldNumber = 7,
    kExpansionTypeFieldNumber = 8,
    kFlowSourcesFieldNumber = 9,
    kTravelModesFieldNumber = 10,
  };
  // repeated uint32 costs = 1 [packed = true];
  int costs_size() const;
  private:
  int _internal_costs_size() const;

  public:
  void clear_costs() ;
  ::uint32_t costs(int index) const;
  void set_costs(int index, ::uint32_t value);
  void add_costs(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& costs() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_costs();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_costs() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_costs();

  public:
  // repeated uint32 durations = 2 [packed = true];
  int durations_size() const;
  private:
  int _internal_durations_size() const;

  public:
  void clear_durations() ;
  ::uint32_t durations(int index) const;
  void set_durations(int index, ::uint32_t value);
  void add_durations(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& durations() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_durations();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_durations() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_durations();

  public:
  // repeated uint32 distances = 3 [packed = true];
  int distances_size() const;
  private:
  int _internal_distances_size() const;

  public:
  void clear_distances() ;
  ::uint32_t distances(int index) const;
  void set_distances(int index, ::uint32_t value);
  void add_distances(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& distances() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_distances();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_distances() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_distances();

  public:
  // repeated .valhalla.Expansion.EdgeStatus edge_status = 4;
  int edge_status_size() const;
  private:
  int _internal_edge_status_size() const;

  public:
  void clear_edge_status() ;
  public:
  ::valhalla::Expansion_EdgeStatus edge_status(int index) const;
  void set_edge_status(int index, ::valhalla::Expansion_EdgeStatus value);
  void add_edge_status(::valhalla::Expansion_EdgeStatus value);
  const ::google::protobuf::RepeatedField<int>& edge_status() const;
  ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL mutable_edge_status();

  private:
  const ::google::protobuf::RepeatedField<int>& _internal_edge_status() const;
  ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL _internal_mutable_edge_status();

  public:
  // repeated uint64 edge_id = 5 [packed = true];
  int edge_id_size() const;
  private:
  int _internal_edge_id_size() const;

  public:
  void clear_edge_id() ;
  ::uint64_t edge_id(int index) const;
  void set_edge_id(int index, ::uint64_t value);
  void add_edge_id(::uint64_t value);
  const ::google::protobuf::RepeatedField<::uint64_t>& edge_id() const;
  ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL mutable_edge_id();

  private:
  const ::google::protobuf::RepeatedField<::uint64_t>& _internal_edge_id() const;
  ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL _internal_mutable_edge_id();

  public:
  // repeated uint64 pred_edge_id = 6 [packed = true];
  int pred_edge_id_size() const;
  private:
  int _internal_pred_edge_id_size() const;

  public:
  void clear_pred_edge_id() ;
  ::uint64_t pred_edge_id(int index) const;
  void set_pred_edge_id(int index, ::uint64_t value);
  void add_pred_edge_id(::uint64_t value);
  const ::google::protobuf::RepeatedField<::uint64_t>& pred_edge_id() const;
  ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL mutable_pred_edge_id();

  private:
  const ::google::protobuf::RepeatedField<::uint64_t>& _internal_pred_edge_id() const;
  ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL _internal_mutable_pred_edge_id();

  public:
  // repeated .valhalla.Expansion.Geometry geometries = 7;
  int geometries_size() const;
  private:
  int _internal_geometries_size() const;

  public:
  void clear_geometries() ;
  ::valhalla::Expansion_Geometry* PROTOBUF_NONNULL mutable_geometries(int index);
  ::google::protobuf::RepeatedPtrField<::valhalla::Expansion_Geometry>* PROTOBUF_NONNULL mutable_geometries();

  private:
  const ::google::protobuf::RepeatedPtrField<::valhalla::Expansion_Geometry>& _internal_geometries() const;
  ::google::protobuf::RepeatedPtrField<::valhalla::Expansion_Geometry>* PROTOBUF_NONNULL _internal_mutable_geometries();
  public:
  const ::valhalla::Expansion_Geometry& geometries(int index) const;
  ::valhalla::Expansion_Geometry* PROTOBUF_NONNULL add_geometries();
  const ::google::protobuf::RepeatedPtrField<::valhalla::Expansion_Geometry>& geometries() const;
  // repeated .valhalla.Expansion.ExpansionType expansion_type = 8;
  int expansion_type_size() const;
  private:
  int _internal_expansion_type_size() const;

  public:
  void clear_expansion_type() ;
  public:
  ::valhalla::Expansion_ExpansionType expansion_type(int index) const;
  void set_expansion_type(int index, ::valhalla::Expansion_ExpansionType value);
  void add_expansion_type(::valhalla::Expansion_ExpansionType value);
  const ::google::protobuf::RepeatedField<int>& expansion_type() const;
  ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL mutable_expansion_type();

  private:
  const ::google::protobuf::RepeatedField<int>& _internal_expansion_type() const;
  ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL _internal_mutable_expansion_type();

  public:
  // repeated uint32 flow_sources = 9 [packed = true];
  int flow_sources_size() const;
  private:
  int _internal_flow_sources_size() const;

  public:
  void clear_flow_sources() ;
  ::uint32_t flow_sources(int index) const;
  void set_flow_sources(int index, ::uint32_t value);
  void add_flow_sources(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& flow_sources() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_flow_sources();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_flow_sources() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_flow_sources();

  public:
  // repeated .valhalla.TravelMode travel_modes = 10 [packed = true];
  int travel_modes_size() const;
  private:
  int _internal_travel_modes_size() const;

  public:
  void clear_travel_modes() ;
  public:
  ::valhalla::TravelMode travel_modes(int index) const;
  void set_travel_modes(int index, ::valhalla::TravelMode value);
  void add_travel_modes(::valhalla::TravelMode value);
  const ::google::protobuf::RepeatedField<int>& travel_modes() const;
  ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL mutable_travel_modes();

  private:
  const ::google::protobuf::RepeatedField<int>& _internal_travel_modes() const;
  ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL _internal_mutable_travel_modes();

  public:
  // @@protoc_insertion_point(class_scope:valhalla.Expansion)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 10,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Expansion& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> costs_;
    ::google::protobuf::internal::CachedSize _costs_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint32_t> durations_;
    ::google::protobuf::internal::CachedSize _durations_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint32_t> distances_;
    ::google::protobuf::internal::CachedSize _distances_cached_byte_size_;
    ::google::protobuf::RepeatedField<int> edge_status_;
    ::google::protobuf::internal::CachedSize _edge_status_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint64_t> edge_id_;
    ::google::protobuf::internal::CachedSize _edge_id_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint64_t> pred_edge_id_;
    ::google::protobuf::internal::CachedSize _pred_edge_id_cached_byte_size_;
    ::google::protobuf::RepeatedPtrField< ::valhalla::Expansion_Geometry > geometries_;
    ::google::protobuf::RepeatedField<int> expansion_type_;
    ::google::protobuf::internal::CachedSize _expansion_type_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint32_t> flow_sources_;
    ::google::protobuf::internal::CachedSize _flow_sources_cached_byte_size_;
    ::google::protobuf::RepeatedField<int> travel_modes_;
    ::google::protobuf::internal::CachedSize _travel_modes_cached_byte_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_expansion_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<19> Expansion_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Expansion_Geometry

// repeated sint32 coords = 1 [packed = true];
inline int Expansion_Geometry::_internal_coords_size() const {
  return _internal_coords().size();
}
inline int Expansion_Geometry::coords_size() const {
  return _internal_coords_size();
}
inline void Expansion_Geometry::clear_coords() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.coords_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t Expansion_Geometry::coords(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.Geometry.coords)
  return _internal_coords().Get(index);
}
inline void Expansion_Geometry::set_coords(int index, ::int32_t value) {
  _internal_mutable_coords()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Expansion.Geometry.coords)
}
inline void Expansion_Geometry::add_coords(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_coords()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.Geometry.coords)
}
inline const ::google::protobuf::RepeatedField<::int32_t>& Expansion_Geometry::coords() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.Geometry.coords)
  return _internal_coords();
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL Expansion_Geometry::mutable_coords()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.Geometry.coords)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_coords();
}
inline const ::google::protobuf::RepeatedField<::int32_t>&
Expansion_Geometry::_internal_coords() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.coords_;
}
inline ::google::protobuf::RepeatedField<::int32_t>* PROTOBUF_NONNULL
Expansion_Geometry::_internal_mutable_coords() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.coords_;
}

// -------------------------------------------------------------------

// Expansion

// repeated uint32 costs = 1 [packed = true];
inline int Expansion::_internal_costs_size() const {
  return _internal_costs().size();
}
inline int Expansion::costs_size() const {
  return _internal_costs_size();
}
inline void Expansion::clear_costs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.costs_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t Expansion::costs(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.costs)
  return _internal_costs().Get(index);
}
inline void Expansion::set_costs(int index, ::uint32_t value) {
  _internal_mutable_costs()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Expansion.costs)
}
inline void Expansion::add_costs(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_costs()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.costs)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& Expansion::costs() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.costs)
  return _internal_costs();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL Expansion::mutable_costs()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.costs)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_costs();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
Expansion::_internal_costs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.costs_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
Expansion::_internal_mutable_costs() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.costs_;
}

// repeated uint32 durations = 2 [packed = true];
inline int Expansion::_internal_durations_size() const {
  return _internal_durations().size();
}
inline int Expansion::durations_size() const {
  return _internal_durations_size();
}
inline void Expansion::clear_durations() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.durations_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t Expansion::durations(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.durations)
  return _internal_durations().Get(index);
}
inline void Expansion::set_durations(int index, ::uint32_t value) {
  _internal_mutable_durations()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Expansion.durations)
}
inline void Expansion::add_durations(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_durations()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.durations)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& Expansion::durations() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.durations)
  return _internal_durations();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL Expansion::mutable_durations()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.durations)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_durations();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
Expansion::_internal_durations() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.durations_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
Expansion::_internal_mutable_durations() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.durations_;
}

// repeated uint32 distances = 3 [packed = true];
inline int Expansion::_internal_distances_size() const {
  return _internal_distances().size();
}
inline int Expansion::distances_size() const {
  return _internal_distances_size();
}
inline void Expansion::clear_distances() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.distances_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t Expansion::distances(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.distances)
  return _internal_distances().Get(index);
}
inline void Expansion::set_distances(int index, ::uint32_t value) {
  _internal_mutable_distances()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Expansion.distances)
}
inline void Expansion::add_distances(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_distances()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.distances)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& Expansion::distances() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.distances)
  return _internal_distances();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL Expansion::mutable_distances()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.distances)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_distances();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
Expansion::_internal_distances() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.distances_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
Expansion::_internal_mutable_distances() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.distances_;
}

// repeated .valhalla.Expansion.EdgeStatus edge_status = 4;
inline int Expansion::_internal_edge_status_size() const {
  return _internal_edge_status().size();
}
inline int Expansion::edge_status_size() const {
  return _internal_edge_status_size();
}
inline void Expansion::clear_edge_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.edge_status_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::valhalla::Expansion_EdgeStatus Expansion::edge_status(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.edge_status)
  return static_cast<::valhalla::Expansion_EdgeStatus>(_internal_edge_status().Get(index));
}
inline void Expansion::set_edge_status(int index, ::valhalla::Expansion_EdgeStatus value) {
  _internal_mutable_edge_status()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Expansion.edge_status)
}
inline void Expansion::add_edge_status(::valhalla::Expansion_EdgeStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_edge_status()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.edge_status)
}
inline const ::google::protobuf::RepeatedField<int>& Expansion::edge_status() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.edge_status)
  return _internal_edge_status();
}
inline ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL Expansion::mutable_edge_status()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.edge_status)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_edge_status();
}
inline const ::google::protobuf::RepeatedField<int>& Expansion::_internal_edge_status()
    const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.edge_status_;
}
inline ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL
Expansion::_internal_mutable_edge_status() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.edge_status_;
}

// repeated uint64 edge_id = 5 [packed = true];
inline int Expansion::_internal_edge_id_size() const {
  return _internal_edge_id().size();
}
inline int Expansion::edge_id_size() const {
  return _internal_edge_id_size();
}
inline void Expansion::clear_edge_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.edge_id_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint64_t Expansion::edge_id(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.edge_id)
  return _internal_edge_id().Get(index);
}
inline void Expansion::set_edge_id(int index, ::uint64_t value) {
  _internal_mutable_edge_id()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Expansion.edge_id)
}
inline void Expansion::add_edge_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_edge_id()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.edge_id)
}
inline const ::google::protobuf::RepeatedField<::uint64_t>& Expansion::edge_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.edge_id)
  return _internal_edge_id();
}
inline ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL Expansion::mutable_edge_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.edge_id)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_edge_id();
}
inline const ::google::protobuf::RepeatedField<::uint64_t>&
Expansion::_internal_edge_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.edge_id_;
}
inline ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL
Expansion::_internal_mutable_edge_id() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.edge_id_;
}

// repeated uint64 pred_edge_id = 6 [packed = true];
inline int Expansion::_internal_pred_edge_id_size() const {
  return _internal_pred_edge_id().size();
}
inline int Expansion::pred_edge_id_size() const {
  return _internal_pred_edge_id_size();
}
inline void Expansion::clear_pred_edge_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pred_edge_id_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint64_t Expansion::pred_edge_id(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.pred_edge_id)
  return _internal_pred_edge_id().Get(index);
}
inline void Expansion::set_pred_edge_id(int index, ::uint64_t value) {
  _internal_mutable_pred_edge_id()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Expansion.pred_edge_id)
}
inline void Expansion::add_pred_edge_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_pred_edge_id()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.pred_edge_id)
}
inline const ::google::protobuf::RepeatedField<::uint64_t>& Expansion::pred_edge_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.pred_edge_id)
  return _internal_pred_edge_id();
}
inline ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL Expansion::mutable_pred_edge_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.pred_edge_id)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pred_edge_id();
}
inline const ::google::protobuf::RepeatedField<::uint64_t>&
Expansion::_internal_pred_edge_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pred_edge_id_;
}
inline ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL
Expansion::_internal_mutable_pred_edge_id() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pred_edge_id_;
}

// repeated .valhalla.Expansion.ExpansionType expansion_type = 8;
inline int Expansion::_internal_expansion_type_size() const {
  return _internal_expansion_type().size();
}
inline int Expansion::expansion_type_size() const {
  return _internal_expansion_type_size();
}
inline void Expansion::clear_expansion_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.expansion_type_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::valhalla::Expansion_ExpansionType Expansion::expansion_type(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.expansion_type)
  return static_cast<::valhalla::Expansion_ExpansionType>(_internal_expansion_type().Get(index));
}
inline void Expansion::set_expansion_type(int index, ::valhalla::Expansion_ExpansionType value) {
  _internal_mutable_expansion_type()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Expansion.expansion_type)
}
inline void Expansion::add_expansion_type(::valhalla::Expansion_ExpansionType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_expansion_type()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.expansion_type)
}
inline const ::google::protobuf::RepeatedField<int>& Expansion::expansion_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.expansion_type)
  return _internal_expansion_type();
}
inline ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL Expansion::mutable_expansion_type()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.expansion_type)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_expansion_type();
}
inline const ::google::protobuf::RepeatedField<int>& Expansion::_internal_expansion_type()
    const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.expansion_type_;
}
inline ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL
Expansion::_internal_mutable_expansion_type() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.expansion_type_;
}

// repeated .valhalla.Expansion.Geometry geometries = 7;
inline int Expansion::_internal_geometries_size() const {
  return _internal_geometries().size();
}
inline int Expansion::geometries_size() const {
  return _internal_geometries_size();
}
inline void Expansion::clear_geometries() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.geometries_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::valhalla::Expansion_Geometry* PROTOBUF_NONNULL Expansion::mutable_geometries(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:valhalla.Expansion.geometries)
  return _internal_mutable_geometries()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::valhalla::Expansion_Geometry>* PROTOBUF_NONNULL Expansion::mutable_geometries()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.geometries)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_geometries();
}
inline const ::valhalla::Expansion_Geometry& Expansion::geometries(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.geometries)
  return _internal_geometries().Get(index);
}
inline ::valhalla::Expansion_Geometry* PROTOBUF_NONNULL Expansion::add_geometries()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::valhalla::Expansion_Geometry* _add =
      _internal_mutable_geometries()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.geometries)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::valhalla::Expansion_Geometry>& Expansion::geometries() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.geometries)
  return _internal_geometries();
}
inline const ::google::protobuf::RepeatedPtrField<::valhalla::Expansion_Geometry>&
Expansion::_internal_geometries() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.geometries_;
}
inline ::google::protobuf::RepeatedPtrField<::valhalla::Expansion_Geometry>* PROTOBUF_NONNULL
Expansion::_internal_mutable_geometries() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.geometries_;
}

// repeated uint32 flow_sources = 9 [packed = true];
inline int Expansion::_internal_flow_sources_size() const {
  return _internal_flow_sources().size();
}
inline int Expansion::flow_sources_size() const {
  return _internal_flow_sources_size();
}
inline void Expansion::clear_flow_sources() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.flow_sources_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::uint32_t Expansion::flow_sources(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.flow_sources)
  return _internal_flow_sources().Get(index);
}
inline void Expansion::set_flow_sources(int index, ::uint32_t value) {
  _internal_mutable_flow_sources()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Expansion.flow_sources)
}
inline void Expansion::add_flow_sources(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_flow_sources()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.flow_sources)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& Expansion::flow_sources() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.flow_sources)
  return _internal_flow_sources();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL Expansion::mutable_flow_sources()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.flow_sources)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_flow_sources();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
Expansion::_internal_flow_sources() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.flow_sources_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
Expansion::_internal_mutable_flow_sources() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.flow_sources_;
}

// repeated .valhalla.TravelMode travel_modes = 10 [packed = true];
inline int Expansion::_internal_travel_modes_size() const {
  return _internal_travel_modes().size();
}
inline int Expansion::travel_modes_size() const {
  return _internal_travel_modes_size();
}
inline void Expansion::clear_travel_modes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.travel_modes_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::valhalla::TravelMode Expansion::travel_modes(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Expansion.travel_modes)
  return static_cast<::valhalla::TravelMode>(_internal_travel_modes().Get(index));
}
inline void Expansion::set_travel_modes(int index, ::valhalla::TravelMode value) {
  _internal_mutable_travel_modes()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Expansion.travel_modes)
}
inline void Expansion::add_travel_modes(::valhalla::TravelMode value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_travel_modes()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_add:valhalla.Expansion.travel_modes)
}
inline const ::google::protobuf::RepeatedField<int>& Expansion::travel_modes() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Expansion.travel_modes)
  return _internal_travel_modes();
}
inline ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL Expansion::mutable_travel_modes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Expansion.travel_modes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_travel_modes();
}
inline const ::google::protobuf::RepeatedField<int>& Expansion::_internal_travel_modes()
    const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.travel_modes_;
}
inline ::google::protobuf::RepeatedField<int>* PROTOBUF_NONNULL
Expansion::_internal_mutable_travel_modes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.travel_modes_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace valhalla


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::valhalla::Expansion_EdgeStatus> : std::true_type {};
template <>
struct is_proto_enum<::valhalla::Expansion_ExpansionType> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // expansion_2eproto_2epb_2eh
