// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: matrix.proto
// Protobuf C++ Version: 6.33.4

#ifndef matrix_2eproto_2epb_2eh
#define matrix_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_util.h"
#include "common.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_matrix_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_matrix_2eproto {
  static const ::uint32_t offsets[];
};
namespace valhalla {
enum Matrix_Algorithm : int;
extern const uint32_t Matrix_Algorithm_internal_data_[];
class Matrix;
struct MatrixDefaultTypeInternal;
extern MatrixDefaultTypeInternal _Matrix_default_instance_;
extern const ::google::protobuf::internal::ClassDataLite<16> Matrix_class_data_;
}  // namespace valhalla
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::valhalla::Matrix_Algorithm_internal_data_>
    internal::EnumTraitsImpl::value<::valhalla::Matrix_Algorithm>;
}  // namespace protobuf
}  // namespace google

namespace valhalla {
enum Matrix_Algorithm : int {
  Matrix_Algorithm_TimeDistanceMatrix = 0,
  Matrix_Algorithm_CostMatrix = 1,
  Matrix_Algorithm_TimeDistanceBSSMatrix = 2,
  Matrix_Algorithm_Matrix_Algorithm_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  Matrix_Algorithm_Matrix_Algorithm_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t Matrix_Algorithm_internal_data_[];
inline constexpr Matrix_Algorithm Matrix_Algorithm_Algorithm_MIN =
    static_cast<Matrix_Algorithm>(0);
inline constexpr Matrix_Algorithm Matrix_Algorithm_Algorithm_MAX =
    static_cast<Matrix_Algorithm>(2);
inline bool Matrix_Algorithm_IsValid(int value) {
  return 0 <= value && value <= 2;
}
inline constexpr int Matrix_Algorithm_Algorithm_ARRAYSIZE = 2 + 1;
const ::std::string& Matrix_Algorithm_Name(Matrix_Algorithm value);
template <typename T>
const ::std::string& Matrix_Algorithm_Name(T value) {
  static_assert(::std::is_same<T, Matrix_Algorithm>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Algorithm_Name().");
  return Matrix_Algorithm_Name(static_cast<Matrix_Algorithm>(value));
}
bool Matrix_Algorithm_Parse(
    ::absl::string_view name, Matrix_Algorithm* PROTOBUF_NONNULL value);

// ===================================================================


// -------------------------------------------------------------------

class Matrix final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:valhalla.Matrix) */ {
 public:
  inline Matrix() : Matrix(nullptr) {}
  ~Matrix() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Matrix* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Matrix));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Matrix(::google::protobuf::internal::ConstantInitialized);

  inline Matrix(const Matrix& from) : Matrix(nullptr, from) {}
  inline Matrix(Matrix&& from) noexcept
      : Matrix(nullptr, ::std::move(from)) {}
  inline Matrix& operator=(const Matrix& from) {
    CopyFrom(from);
    return *this;
  }
  inline Matrix& operator=(Matrix&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  inline ::std::string* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  static const Matrix& default_instance() {
    return *reinterpret_cast<const Matrix*>(
        &_Matrix_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Matrix& a, Matrix& b) { a.Swap(&b); }
  inline void Swap(Matrix* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Matrix* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Matrix* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<Matrix>(arena);
  }
  void CopyFrom(const Matrix& from);
  void MergeFrom(const Matrix& from) { Matrix::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Matrix* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "valhalla.Matrix"; }

  explicit Matrix(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Matrix(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Matrix& from);
  Matrix(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Matrix&& from) noexcept
      : Matrix(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  // nested types ----------------------------------------------------
  using Algorithm = Matrix_Algorithm;
  static constexpr Algorithm TimeDistanceMatrix = Matrix_Algorithm_TimeDistanceMatrix;
  static constexpr Algorithm CostMatrix = Matrix_Algorithm_CostMatrix;
  static constexpr Algorithm TimeDistanceBSSMatrix = Matrix_Algorithm_TimeDistanceBSSMatrix;
  static inline bool Algorithm_IsValid(int value) {
    return Matrix_Algorithm_IsValid(value);
  }
  static constexpr Algorithm Algorithm_MIN = Matrix_Algorithm_Algorithm_MIN;
  static constexpr Algorithm Algorithm_MAX = Matrix_Algorithm_Algorithm_MAX;
  static constexpr int Algorithm_ARRAYSIZE = Matrix_Algorithm_Algorithm_ARRAYSIZE;
  template <typename T>
  static inline const ::std::string& Algorithm_Name(T value) {
    return Matrix_Algorithm_Name(value);
  }
  static inline bool Algorithm_Parse(
      ::absl::string_view name, Algorithm* PROTOBUF_NONNULL value) {
    return Matrix_Algorithm_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kDistancesFieldNumber = 2,
    kTimesFieldNumber = 3,
    kFromIndicesFieldNumber = 4,
    kToIndicesFieldNumber = 5,
    kDateTimesFieldNumber = 6,
    kShapesFieldNumber = 8,
    kTimeZoneOffsetsFieldNumber = 9,
    kTimeZoneNamesFieldNumber = 10,
    kSecondPassFieldNumber = 11,
    kBeginHeadingFieldNumber = 12,
    kEndHeadingFieldNumber = 13,
    kBeginLatFieldNumber = 14,
    kBeginLonFieldNumber = 15,
    kEndLatFieldNumber = 16,
    kEndLonFieldNumber = 17,
    kAlgorithmFieldNumber = 7,
  };
  // repeated uint32 distances = 2;
  int distances_size() const;
  private:
  int _internal_distances_size() const;

  public:
  void clear_distances() ;
  ::uint32_t distances(int index) const;
  void set_distances(int index, ::uint32_t value);
  void add_distances(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& distances() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_distances();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_distances() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_distances();

  public:
  // repeated float times = 3;
  int times_size() const;
  private:
  int _internal_times_size() const;

  public:
  void clear_times() ;
  float times(int index) const;
  void set_times(int index, float value);
  void add_times(float value);
  const ::google::protobuf::RepeatedField<float>& times() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_times();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_times() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_times();

  public:
  // repeated uint32 from_indices = 4;
  int from_indices_size() const;
  private:
  int _internal_from_indices_size() const;

  public:
  void clear_from_indices() ;
  ::uint32_t from_indices(int index) const;
  void set_from_indices(int index, ::uint32_t value);
  void add_from_indices(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& from_indices() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_from_indices();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_from_indices() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_from_indices();

  public:
  // repeated uint32 to_indices = 5;
  int to_indices_size() const;
  private:
  int _internal_to_indices_size() const;

  public:
  void clear_to_indices() ;
  ::uint32_t to_indices(int index) const;
  void set_to_indices(int index, ::uint32_t value);
  void add_to_indices(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& to_indices() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_to_indices();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_to_indices() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_to_indices();

  public:
  // repeated string date_times = 6;
  int date_times_size() const;
  private:
  int _internal_date_times_size() const;

  public:
  void clear_date_times() ;
  const ::std::string& date_times(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_date_times(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_date_times(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_date_times();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_date_times(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& date_times() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_date_times();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_date_times() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_date_times();

  public:
  // repeated string shapes = 8;
  int shapes_size() const;
  private:
  int _internal_shapes_size() const;

  public:
  void clear_shapes() ;
  const ::std::string& shapes(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_shapes(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_shapes(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_shapes();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_shapes(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& shapes() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_shapes();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_shapes() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_shapes();

  public:
  // repeated string time_zone_offsets = 9;
  int time_zone_offsets_size() const;
  private:
  int _internal_time_zone_offsets_size() const;

  public:
  void clear_time_zone_offsets() ;
  const ::std::string& time_zone_offsets(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_time_zone_offsets(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_time_zone_offsets(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_time_zone_offsets();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_time_zone_offsets(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& time_zone_offsets() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_time_zone_offsets();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_time_zone_offsets() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_time_zone_offsets();

  public:
  // repeated string time_zone_names = 10;
  int time_zone_names_size() const;
  private:
  int _internal_time_zone_names_size() const;

  public:
  void clear_time_zone_names() ;
  const ::std::string& time_zone_names(int index) const;
  ::std::string* PROTOBUF_NONNULL mutable_time_zone_names(int index);
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_time_zone_names(int index, Arg_&& value, Args_... args);
  ::std::string* PROTOBUF_NONNULL add_time_zone_names();
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void add_time_zone_names(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<::std::string>& time_zone_names() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL mutable_time_zone_names();

  private:
  const ::google::protobuf::RepeatedPtrField<::std::string>& _internal_time_zone_names() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL _internal_mutable_time_zone_names();

  public:
  // repeated bool second_pass = 11;
  int second_pass_size() const;
  private:
  int _internal_second_pass_size() const;

  public:
  void clear_second_pass() ;
  bool second_pass(int index) const;
  void set_second_pass(int index, bool value);
  void add_second_pass(bool value);
  const ::google::protobuf::RepeatedField<bool>& second_pass() const;
  ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL mutable_second_pass();

  private:
  const ::google::protobuf::RepeatedField<bool>& _internal_second_pass() const;
  ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL _internal_mutable_second_pass();

  public:
  // repeated float begin_heading = 12;
  int begin_heading_size() const;
  private:
  int _internal_begin_heading_size() const;

  public:
  void clear_begin_heading() ;
  float begin_heading(int index) const;
  void set_begin_heading(int index, float value);
  void add_begin_heading(float value);
  const ::google::protobuf::RepeatedField<float>& begin_heading() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_begin_heading();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_begin_heading() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_begin_heading();

  public:
  // repeated float end_heading = 13;
  int end_heading_size() const;
  private:
  int _internal_end_heading_size() const;

  public:
  void clear_end_heading() ;
  float end_heading(int index) const;
  void set_end_heading(int index, float value);
  void add_end_heading(float value);
  const ::google::protobuf::RepeatedField<float>& end_heading() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL mutable_end_heading();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_end_heading() const;
  ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL _internal_mutable_end_heading();

  public:
  // repeated double begin_lat = 14;
  int begin_lat_size() const;
  private:
  int _internal_begin_lat_size() const;

  public:
  void clear_begin_lat() ;
  double begin_lat(int index) const;
  void set_begin_lat(int index, double value);
  void add_begin_lat(double value);
  const ::google::protobuf::RepeatedField<double>& begin_lat() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_begin_lat();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_begin_lat() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_begin_lat();

  public:
  // repeated double begin_lon = 15;
  int begin_lon_size() const;
  private:
  int _internal_begin_lon_size() const;

  public:
  void clear_begin_lon() ;
  double begin_lon(int index) const;
  void set_begin_lon(int index, double value);
  void add_begin_lon(double value);
  const ::google::protobuf::RepeatedField<double>& begin_lon() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_begin_lon();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_begin_lon() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_begin_lon();

  public:
  // repeated double end_lat = 16;
  int end_lat_size() const;
  private:
  int _internal_end_lat_size() const;

  public:
  void clear_end_lat() ;
  double end_lat(int index) const;
  void set_end_lat(int index, double value);
  void add_end_lat(double value);
  const ::google::protobuf::RepeatedField<double>& end_lat() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_end_lat();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_end_lat() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_end_lat();

  public:
  // repeated double end_lon = 17;
  int end_lon_size() const;
  private:
  int _internal_end_lon_size() const;

  public:
  void clear_end_lon() ;
  double end_lon(int index) const;
  void set_end_lon(int index, double value);
  void add_end_lon(double value);
  const ::google::protobuf::RepeatedField<double>& end_lon() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL mutable_end_lon();

  private:
  const ::google::protobuf::RepeatedField<double>& _internal_end_lon() const;
  ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL _internal_mutable_end_lon();

  public:
  // .valhalla.Matrix.Algorithm algorithm = 7;
  void clear_algorithm() ;
  ::valhalla::Matrix_Algorithm algorithm() const;
  void set_algorithm(::valhalla::Matrix_Algorithm value);

  private:
  ::valhalla::Matrix_Algorithm _internal_algorithm() const;
  void _internal_set_algorithm(::valhalla::Matrix_Algorithm value);

  public:
  // @@protoc_insertion_point(class_scope:valhalla.Matrix)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 16,
                                   0, 88,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Matrix& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> distances_;
    ::google::protobuf::internal::CachedSize _distances_cached_byte_size_;
    ::google::protobuf::RepeatedField<float> times_;
    ::google::protobuf::RepeatedField<::uint32_t> from_indices_;
    ::google::protobuf::internal::CachedSize _from_indices_cached_byte_size_;
    ::google::protobuf::RepeatedField<::uint32_t> to_indices_;
    ::google::protobuf::internal::CachedSize _to_indices_cached_byte_size_;
    ::google::protobuf::RepeatedPtrField<::std::string> date_times_;
    ::google::protobuf::RepeatedPtrField<::std::string> shapes_;
    ::google::protobuf::RepeatedPtrField<::std::string> time_zone_offsets_;
    ::google::protobuf::RepeatedPtrField<::std::string> time_zone_names_;
    ::google::protobuf::RepeatedField<bool> second_pass_;
    ::google::protobuf::RepeatedField<float> begin_heading_;
    ::google::protobuf::RepeatedField<float> end_heading_;
    ::google::protobuf::RepeatedField<double> begin_lat_;
    ::google::protobuf::RepeatedField<double> begin_lon_;
    ::google::protobuf::RepeatedField<double> end_lat_;
    ::google::protobuf::RepeatedField<double> end_lon_;
    int algorithm_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_matrix_2eproto;
};

extern const ::google::protobuf::internal::ClassDataLite<16> Matrix_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Matrix

// repeated uint32 distances = 2;
inline int Matrix::_internal_distances_size() const {
  return _internal_distances().size();
}
inline int Matrix::distances_size() const {
  return _internal_distances_size();
}
inline void Matrix::clear_distances() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.distances_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t Matrix::distances(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.distances)
  return _internal_distances().Get(index);
}
inline void Matrix::set_distances(int index, ::uint32_t value) {
  _internal_mutable_distances()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.distances)
}
inline void Matrix::add_distances(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_distances()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.distances)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& Matrix::distances() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.distances)
  return _internal_distances();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL Matrix::mutable_distances()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.distances)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_distances();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
Matrix::_internal_distances() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.distances_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
Matrix::_internal_mutable_distances() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.distances_;
}

// repeated float times = 3;
inline int Matrix::_internal_times_size() const {
  return _internal_times().size();
}
inline int Matrix::times_size() const {
  return _internal_times_size();
}
inline void Matrix::clear_times() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.times_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000002U);
}
inline float Matrix::times(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.times)
  return _internal_times().Get(index);
}
inline void Matrix::set_times(int index, float value) {
  _internal_mutable_times()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.times)
}
inline void Matrix::add_times(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_times()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.times)
}
inline const ::google::protobuf::RepeatedField<float>& Matrix::times() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.times)
  return _internal_times();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL Matrix::mutable_times()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.times)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_times();
}
inline const ::google::protobuf::RepeatedField<float>&
Matrix::_internal_times() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.times_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
Matrix::_internal_mutable_times() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.times_;
}

// repeated uint32 from_indices = 4;
inline int Matrix::_internal_from_indices_size() const {
  return _internal_from_indices().size();
}
inline int Matrix::from_indices_size() const {
  return _internal_from_indices_size();
}
inline void Matrix::clear_from_indices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.from_indices_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t Matrix::from_indices(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.from_indices)
  return _internal_from_indices().Get(index);
}
inline void Matrix::set_from_indices(int index, ::uint32_t value) {
  _internal_mutable_from_indices()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.from_indices)
}
inline void Matrix::add_from_indices(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_from_indices()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.from_indices)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& Matrix::from_indices() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.from_indices)
  return _internal_from_indices();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL Matrix::mutable_from_indices()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.from_indices)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_from_indices();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
Matrix::_internal_from_indices() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.from_indices_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
Matrix::_internal_mutable_from_indices() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.from_indices_;
}

// repeated uint32 to_indices = 5;
inline int Matrix::_internal_to_indices_size() const {
  return _internal_to_indices().size();
}
inline int Matrix::to_indices_size() const {
  return _internal_to_indices_size();
}
inline void Matrix::clear_to_indices() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.to_indices_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t Matrix::to_indices(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.to_indices)
  return _internal_to_indices().Get(index);
}
inline void Matrix::set_to_indices(int index, ::uint32_t value) {
  _internal_mutable_to_indices()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.to_indices)
}
inline void Matrix::add_to_indices(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_to_indices()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.to_indices)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& Matrix::to_indices() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.to_indices)
  return _internal_to_indices();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL Matrix::mutable_to_indices()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.to_indices)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_to_indices();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
Matrix::_internal_to_indices() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.to_indices_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
Matrix::_internal_mutable_to_indices() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.to_indices_;
}

// repeated string date_times = 6;
inline int Matrix::_internal_date_times_size() const {
  return _internal_date_times().size();
}
inline int Matrix::date_times_size() const {
  return _internal_date_times_size();
}
inline void Matrix::clear_date_times() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.date_times_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::std::string* PROTOBUF_NONNULL Matrix::add_date_times()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_date_times()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_add_mutable:valhalla.Matrix.date_times)
  return _s;
}
inline const ::std::string& Matrix::date_times(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.date_times)
  return _internal_date_times().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL Matrix::mutable_date_times(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:valhalla.Matrix.date_times)
  return _internal_mutable_date_times()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void Matrix::set_date_times(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_date_times()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:valhalla.Matrix.date_times)
}
template <typename Arg_, typename... Args_>
inline void Matrix::add_date_times(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_date_times(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.date_times)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& Matrix::date_times()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.date_times)
  return _internal_date_times();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Matrix::mutable_date_times() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.date_times)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_date_times();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Matrix::_internal_date_times() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.date_times_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Matrix::_internal_mutable_date_times() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.date_times_;
}

// .valhalla.Matrix.Algorithm algorithm = 7;
inline void Matrix::clear_algorithm() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.algorithm_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00008000U);
}
inline ::valhalla::Matrix_Algorithm Matrix::algorithm() const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.algorithm)
  return _internal_algorithm();
}
inline void Matrix::set_algorithm(::valhalla::Matrix_Algorithm value) {
  _internal_set_algorithm(value);
  SetHasBit(_impl_._has_bits_[0], 0x00008000U);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.algorithm)
}
inline ::valhalla::Matrix_Algorithm Matrix::_internal_algorithm() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::valhalla::Matrix_Algorithm>(_impl_.algorithm_);
}
inline void Matrix::_internal_set_algorithm(::valhalla::Matrix_Algorithm value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.algorithm_ = value;
}

// repeated string shapes = 8;
inline int Matrix::_internal_shapes_size() const {
  return _internal_shapes().size();
}
inline int Matrix::shapes_size() const {
  return _internal_shapes_size();
}
inline void Matrix::clear_shapes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.shapes_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::std::string* PROTOBUF_NONNULL Matrix::add_shapes()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_shapes()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_add_mutable:valhalla.Matrix.shapes)
  return _s;
}
inline const ::std::string& Matrix::shapes(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.shapes)
  return _internal_shapes().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL Matrix::mutable_shapes(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:valhalla.Matrix.shapes)
  return _internal_mutable_shapes()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void Matrix::set_shapes(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_shapes()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:valhalla.Matrix.shapes)
}
template <typename Arg_, typename... Args_>
inline void Matrix::add_shapes(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_shapes(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.shapes)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& Matrix::shapes()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.shapes)
  return _internal_shapes();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Matrix::mutable_shapes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.shapes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_shapes();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Matrix::_internal_shapes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.shapes_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Matrix::_internal_mutable_shapes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.shapes_;
}

// repeated string time_zone_offsets = 9;
inline int Matrix::_internal_time_zone_offsets_size() const {
  return _internal_time_zone_offsets().size();
}
inline int Matrix::time_zone_offsets_size() const {
  return _internal_time_zone_offsets_size();
}
inline void Matrix::clear_time_zone_offsets() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_zone_offsets_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::std::string* PROTOBUF_NONNULL Matrix::add_time_zone_offsets()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_time_zone_offsets()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_add_mutable:valhalla.Matrix.time_zone_offsets)
  return _s;
}
inline const ::std::string& Matrix::time_zone_offsets(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.time_zone_offsets)
  return _internal_time_zone_offsets().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL Matrix::mutable_time_zone_offsets(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:valhalla.Matrix.time_zone_offsets)
  return _internal_mutable_time_zone_offsets()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void Matrix::set_time_zone_offsets(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_time_zone_offsets()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:valhalla.Matrix.time_zone_offsets)
}
template <typename Arg_, typename... Args_>
inline void Matrix::add_time_zone_offsets(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_time_zone_offsets(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.time_zone_offsets)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& Matrix::time_zone_offsets()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.time_zone_offsets)
  return _internal_time_zone_offsets();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Matrix::mutable_time_zone_offsets() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.time_zone_offsets)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_time_zone_offsets();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Matrix::_internal_time_zone_offsets() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_zone_offsets_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Matrix::_internal_mutable_time_zone_offsets() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.time_zone_offsets_;
}

// repeated string time_zone_names = 10;
inline int Matrix::_internal_time_zone_names_size() const {
  return _internal_time_zone_names().size();
}
inline int Matrix::time_zone_names_size() const {
  return _internal_time_zone_names_size();
}
inline void Matrix::clear_time_zone_names() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.time_zone_names_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::std::string* PROTOBUF_NONNULL Matrix::add_time_zone_names()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::std::string* _s =
      _internal_mutable_time_zone_names()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_add_mutable:valhalla.Matrix.time_zone_names)
  return _s;
}
inline const ::std::string& Matrix::time_zone_names(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.time_zone_names)
  return _internal_time_zone_names().Get(index);
}
inline ::std::string* PROTOBUF_NONNULL Matrix::mutable_time_zone_names(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:valhalla.Matrix.time_zone_names)
  return _internal_mutable_time_zone_names()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void Matrix::set_time_zone_names(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(*_internal_mutable_time_zone_names()->Mutable(index), ::std::forward<Arg_>(value),
                        args... );
  // @@protoc_insertion_point(field_set:valhalla.Matrix.time_zone_names)
}
template <typename Arg_, typename... Args_>
inline void Matrix::add_time_zone_names(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(
      ::google::protobuf::MessageLite::internal_visibility(), GetArena(),
      *_internal_mutable_time_zone_names(), ::std::forward<Arg_>(value),
      args... );
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.time_zone_names)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>& Matrix::time_zone_names()
    const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.time_zone_names)
  return _internal_time_zone_names();
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Matrix::mutable_time_zone_names() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.time_zone_names)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_time_zone_names();
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Matrix::_internal_time_zone_names() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.time_zone_names_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>* PROTOBUF_NONNULL
Matrix::_internal_mutable_time_zone_names() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.time_zone_names_;
}

// repeated bool second_pass = 11;
inline int Matrix::_internal_second_pass_size() const {
  return _internal_second_pass().size();
}
inline int Matrix::second_pass_size() const {
  return _internal_second_pass_size();
}
inline void Matrix::clear_second_pass() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.second_pass_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000100U);
}
inline bool Matrix::second_pass(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.second_pass)
  return _internal_second_pass().Get(index);
}
inline void Matrix::set_second_pass(int index, bool value) {
  _internal_mutable_second_pass()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.second_pass)
}
inline void Matrix::add_second_pass(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_second_pass()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.second_pass)
}
inline const ::google::protobuf::RepeatedField<bool>& Matrix::second_pass() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.second_pass)
  return _internal_second_pass();
}
inline ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL Matrix::mutable_second_pass()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.second_pass)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_second_pass();
}
inline const ::google::protobuf::RepeatedField<bool>&
Matrix::_internal_second_pass() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.second_pass_;
}
inline ::google::protobuf::RepeatedField<bool>* PROTOBUF_NONNULL
Matrix::_internal_mutable_second_pass() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.second_pass_;
}

// repeated float begin_heading = 12;
inline int Matrix::_internal_begin_heading_size() const {
  return _internal_begin_heading().size();
}
inline int Matrix::begin_heading_size() const {
  return _internal_begin_heading_size();
}
inline void Matrix::clear_begin_heading() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.begin_heading_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000200U);
}
inline float Matrix::begin_heading(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.begin_heading)
  return _internal_begin_heading().Get(index);
}
inline void Matrix::set_begin_heading(int index, float value) {
  _internal_mutable_begin_heading()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.begin_heading)
}
inline void Matrix::add_begin_heading(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_begin_heading()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.begin_heading)
}
inline const ::google::protobuf::RepeatedField<float>& Matrix::begin_heading() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.begin_heading)
  return _internal_begin_heading();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL Matrix::mutable_begin_heading()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.begin_heading)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_begin_heading();
}
inline const ::google::protobuf::RepeatedField<float>&
Matrix::_internal_begin_heading() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.begin_heading_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
Matrix::_internal_mutable_begin_heading() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.begin_heading_;
}

// repeated float end_heading = 13;
inline int Matrix::_internal_end_heading_size() const {
  return _internal_end_heading().size();
}
inline int Matrix::end_heading_size() const {
  return _internal_end_heading_size();
}
inline void Matrix::clear_end_heading() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_heading_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000400U);
}
inline float Matrix::end_heading(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.end_heading)
  return _internal_end_heading().Get(index);
}
inline void Matrix::set_end_heading(int index, float value) {
  _internal_mutable_end_heading()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.end_heading)
}
inline void Matrix::add_end_heading(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_end_heading()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.end_heading)
}
inline const ::google::protobuf::RepeatedField<float>& Matrix::end_heading() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.end_heading)
  return _internal_end_heading();
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL Matrix::mutable_end_heading()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.end_heading)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_end_heading();
}
inline const ::google::protobuf::RepeatedField<float>&
Matrix::_internal_end_heading() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.end_heading_;
}
inline ::google::protobuf::RepeatedField<float>* PROTOBUF_NONNULL
Matrix::_internal_mutable_end_heading() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.end_heading_;
}

// repeated double begin_lat = 14;
inline int Matrix::_internal_begin_lat_size() const {
  return _internal_begin_lat().size();
}
inline int Matrix::begin_lat_size() const {
  return _internal_begin_lat_size();
}
inline void Matrix::clear_begin_lat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.begin_lat_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000800U);
}
inline double Matrix::begin_lat(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.begin_lat)
  return _internal_begin_lat().Get(index);
}
inline void Matrix::set_begin_lat(int index, double value) {
  _internal_mutable_begin_lat()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.begin_lat)
}
inline void Matrix::add_begin_lat(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_begin_lat()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.begin_lat)
}
inline const ::google::protobuf::RepeatedField<double>& Matrix::begin_lat() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.begin_lat)
  return _internal_begin_lat();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL Matrix::mutable_begin_lat()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.begin_lat)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_begin_lat();
}
inline const ::google::protobuf::RepeatedField<double>&
Matrix::_internal_begin_lat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.begin_lat_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
Matrix::_internal_mutable_begin_lat() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.begin_lat_;
}

// repeated double begin_lon = 15;
inline int Matrix::_internal_begin_lon_size() const {
  return _internal_begin_lon().size();
}
inline int Matrix::begin_lon_size() const {
  return _internal_begin_lon_size();
}
inline void Matrix::clear_begin_lon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.begin_lon_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00001000U);
}
inline double Matrix::begin_lon(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.begin_lon)
  return _internal_begin_lon().Get(index);
}
inline void Matrix::set_begin_lon(int index, double value) {
  _internal_mutable_begin_lon()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.begin_lon)
}
inline void Matrix::add_begin_lon(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_begin_lon()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.begin_lon)
}
inline const ::google::protobuf::RepeatedField<double>& Matrix::begin_lon() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.begin_lon)
  return _internal_begin_lon();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL Matrix::mutable_begin_lon()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.begin_lon)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_begin_lon();
}
inline const ::google::protobuf::RepeatedField<double>&
Matrix::_internal_begin_lon() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.begin_lon_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
Matrix::_internal_mutable_begin_lon() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.begin_lon_;
}

// repeated double end_lat = 16;
inline int Matrix::_internal_end_lat_size() const {
  return _internal_end_lat().size();
}
inline int Matrix::end_lat_size() const {
  return _internal_end_lat_size();
}
inline void Matrix::clear_end_lat() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_lat_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00002000U);
}
inline double Matrix::end_lat(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.end_lat)
  return _internal_end_lat().Get(index);
}
inline void Matrix::set_end_lat(int index, double value) {
  _internal_mutable_end_lat()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.end_lat)
}
inline void Matrix::add_end_lat(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_end_lat()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.end_lat)
}
inline const ::google::protobuf::RepeatedField<double>& Matrix::end_lat() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.end_lat)
  return _internal_end_lat();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL Matrix::mutable_end_lat()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.end_lat)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_end_lat();
}
inline const ::google::protobuf::RepeatedField<double>&
Matrix::_internal_end_lat() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.end_lat_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
Matrix::_internal_mutable_end_lat() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.end_lat_;
}

// repeated double end_lon = 17;
inline int Matrix::_internal_end_lon_size() const {
  return _internal_end_lon().size();
}
inline int Matrix::end_lon_size() const {
  return _internal_end_lon_size();
}
inline void Matrix::clear_end_lon() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_lon_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00004000U);
}
inline double Matrix::end_lon(int index) const {
  // @@protoc_insertion_point(field_get:valhalla.Matrix.end_lon)
  return _internal_end_lon().Get(index);
}
inline void Matrix::set_end_lon(int index, double value) {
  _internal_mutable_end_lon()->Set(index, value);
  // @@protoc_insertion_point(field_set:valhalla.Matrix.end_lon)
}
inline void Matrix::add_end_lon(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_end_lon()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_add:valhalla.Matrix.end_lon)
}
inline const ::google::protobuf::RepeatedField<double>& Matrix::end_lon() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:valhalla.Matrix.end_lon)
  return _internal_end_lon();
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL Matrix::mutable_end_lon()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00004000U);
  // @@protoc_insertion_point(field_mutable_list:valhalla.Matrix.end_lon)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_end_lon();
}
inline const ::google::protobuf::RepeatedField<double>&
Matrix::_internal_end_lon() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.end_lon_;
}
inline ::google::protobuf::RepeatedField<double>* PROTOBUF_NONNULL
Matrix::_internal_mutable_end_lon() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.end_lon_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace valhalla


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::valhalla::Matrix_Algorithm> : std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // matrix_2eproto_2epb_2eh
